INSERT INTO inventory (business, brand, can_size, on_hand, PSL, shrink) VALUES 
('Main St Brewing', 'Naked Fox IPA', '355ml STD', 12076, false, true),
('Main St Brewing', 'Main St Pilsner', '355ml STD', 12076, false, true),
('Main St Brewing', 'Hazy Chain', '355ml STD', 0, false, true),
('Main St Brewing', 'Hula Hula Shake', '473ml STD', 560, true, false),
('Main St Brewing', 'Kingpin Pale Ale', '355ml STD', 6725, false, true),
('Main St Brewing', 'Tunnerman Ale', '473ml STD', 8976, true, false),
('Brassneck', 'Californiacation', '473ml STD', 40987, true, false),
('Brassneck', 'Raspberry Changling', '473ml STD', 9876, true, false),
('Brassneck', 'Unconventional Wisdom', '473ml STD', 40987, true, false),
('Brassneck', 'Klutz Kolsch', '473ml STD', 40987, true, false),
('Brassneck', 'No Brainer', '473ml STD', 40987, true, false),
('Brassneck', 'Passive Aggressive', '473ml STD', 40987, true, false),
('Strathcona', 'Strath Lager', '355ml STD', 7654, false, true),
('Strathcona', 'Lemon Mandarin Radler', '355ml STD', 3773, false, true),
('Strathcona', 'Premium Pilsner', '355ml STD', 10987, true, false),
('Strathcona', 'Love Buzz', '473ml STD', 16534, false, true),
('Strathcona', 'Beautiful Pale Ale', '473ml STD', 430, false, true),
('Strathcona', 'Smash Bombs Double IPA', '473 STD', 6728, false, true),
('Strathcona', 'Head Banger IPA', '473ml STD', 873, true, false),
('Studio Brewing', 'Infinite Radness', '355ml STD', 3876, true, false),
('Studio Brewing', 'Sun Jungle', '355ml STD', 1775, true, false),
('Studio Brewing', 'Felix', '355ml STD', 376, true, false),
('Studio Brewing', 'Daisy Chain', '355ml STD', 7543, true, false),
('Studio Brewing', 'Embarassment of Riches', '355ml STD', 1234, true, false),
('Studio Brewing', 'Rookie Card Vienna Lager V2', '355ml STD', 2431, true, false),
('Studio Brewing', 'Ghost Writer Sour Saison', '355ml STD', 987, true, false),
('Studio Brewing', 'Rolodex American Pale Ale V2', '355ml STD', 67, true, false),
('Studio Brewing', 'Marketplatz German Pilsner', '355ml STD', 985, true, false),
